### ISSUE TITLE
Local build error (v7.0-beta28)

### ISSUE THREAD

**Issue by vinzlee97** [subframe7536/Maple-font#262]
Here's the stack trace:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "~/.pyenv/versions/3.12.6/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.12.6/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "~/Repositories/Maple-font/build.py", line 483, in build_nf
    if font_config.should_use_font_patcher()
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Repositories/Maple-font/build.py", line 191, in should_use_font_patcher
    if check_font_patcher(version=self.nerd_font["version"]) and not path.exists(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/Repositories/Maple-font/build.py", line 289, in check_font_patcher
    zip_ref.extractall("FontPatcher")
  File "~/.pyenv/versions/3.12.6/lib/python3.12/zipfile/__init__.py", line 1744, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "~/.pyenv/versions/3.12.6/lib/python3.12/zipfile/__init__.py", line 1802, in _extract_member
    shutil.copyfileobj(source, target)
  File "~/.pyenv/versions/3.12.6/lib/python3.12/shutil.py", line 203, in copyfileobj
    while buf := fsrc_read(length):
                 ^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.12.6/lib/python3.12/zipfile/__init__.py", line 989, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.12.6/lib/python3.12/zipfile/__init__.py", line 1079, in _read1
    self._update_crc(data)
  File "~/.pyenv/versions/3.12.6/lib/python3.12/zipfile/__init__.py", line 1007, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'src/glyphs/weather-icons/OFL-FAQ.txt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/Repositories/Maple-font/build.py", line 840, in <module>
    main()
  File "~/Repositories/Maple-font/build.py", line 698, in main
    p.map(_build_fn, listdir(build_option.output_ttf))
  File "~/.pyenv/versions/3.12.6/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.12.6/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
zipfile.BadZipFile: Bad CRC-32 for file 'src/glyphs/weather-icons/OFL-FAQ.txt'
```

And here's my `config.json`:
```json
{
  "$schema": "./source/schema.json",
  "family_name": "Maple Mono",
  "use_hinted": true,
  "pool_size": 4,
  "feature_freeze": {
    "cv01": "enable",
    "cv02": "enable",
    "cv03": "enable",
    "cv04": "ignore",
    "cv31": "ignore",
    "cv32": "ignore",
    "cv33": "ignore",
    "cv34": "ignore",
    "cv35": "ignore",
    "cv36": "ignore",
    "cv98": "ignore",
    "cv99": "ignore",
    "ss01": "ignore",
    "ss02": "ignore",
    "ss03": "enable",
    "ss04": "ignore",
    "ss05": "enable",
    "ss06": "ignore",
    "ss07": "ignore",
    "zero": "enable"
  },
  "nerd_font": {
    "enable": true,
    "version": "3.2.1",
    "mono": true,
    "use_font_patcher": true,
    "glyphs": [
      "--complete"
    ],
    "extra_args": []
  },
  "cn": {
    "enable": true,
    "with_nerd_font": true,
    "fix_meta_table": true,
    "clean_cache": false,
    "narrow": false,
    "use_hinted": false
  }
}
```

**Comment by subframe7536** [comment]
Nice catch, I fixed it.
