### ISSUE TITLE
Failed to build nerd font with font-patcher

### ISSUE THREAD

**Issue by atauzki** [subframe7536/maple-font#289]
cmdline: `python ./build.py --no-hinted --feat cv01,cv02`
config:
```
{
  "$schema": "./source/schema.json",
  "family_name": "Maple Term NF33",
  "use_hinted": true,
  "pool_size": 4,
  "ligature": true,
  "feature_freeze": {
    "cv01": "ignore",
    "cv02": "ignore",
    "cv03": "ignore",
    "cv04": "ignore",
    "cv31": "ignore",
    "cv32": "ignore",
    "cv33": "ignore",
    "cv34": "ignore",
    "cv35": "ignore",
    "cv36": "ignore",
    "cv98": "ignore",
    "cv99": "ignore",
    "ss01": "ignore",
    "ss02": "ignore",
    "ss03": "ignore",
    "ss04": "ignore",
    "ss05": "ignore",
    "ss06": "ignore",
    "ss07": "ignore",
    "ss08": "ignore",
    "zero": "ignore"
  },
  "nerd_font": {
    "enable": true,
    "version": "3.3.0",
    "mono": false,
    "use_font_patcher": true,
    "glyphs": [
      "--complete"
    ],
    "extra_args": []
  },
  "cn": {
    "enable": false,
    "with_nerd_font": true,
    "fix_meta_table": true,
    "clean_cache": false,
    "narrow": false,
    "use_hinted": false,
    "use_static_base_font": true
  }
}
```

error log:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/hp/miniconda3/envs/maple/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/hp/miniconda3/envs/maple/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/hp/Projects/maple-font/./build.py", line 656, in build_nf
    nf_font = get_ttfont(f)
              ^^^^^^^^^^^^^
  File "/home/hp/Projects/maple-font/./build.py", line 643, in build_nf_by_font_patcher
    font = TTFont(_path)
           ^^^^^^^^^^^^^
  File "/home/hp/miniconda3/envs/maple/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 145, in __init__
    file = open(file, "rb")
           ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'fonts/NF/MapleMonoNerdFont-ExtraBold.ttf'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hp/Projects/maple-font/./build.py", line 1048, in <module>
    main()
  File "/home/hp/Projects/maple-font/./build.py", line 898, in main
    run_build(font_config.pool_size, _build_fn, build_option.output_ttf)
  File "/home/hp/Projects/maple-font/./build.py", line 788, in run_build
    p.map(fn, listdir(dir))
  File "/home/hp/miniconda3/envs/maple/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hp/miniconda3/envs/maple/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'fonts/NF/MapleMonoNerdFont-ExtraBold.ttf'
```
generated font names:
```
-rw-r--r-- 1 hp hp 2382260 12月 4日 21:16 MapleTermNF33NerdFont-BoldItalic.ttf
-rw-r--r-- 1 hp hp 2361420 12月 4日 21:15 MapleTermNF33NerdFont-Bold.ttf
-rw-r--r-- 1 hp hp 2381764 12月 4日 21:15 MapleTermNF33NerdFont-ExtraBoldItalic.ttf
-rw-r--r-- 1 hp hp 2361116 12月 4日 21:15 MapleTermNF33NerdFont-ExtraBold.ttf
-rw-r--r-- 1 hp hp 2382908 12月 4日 21:16 MapleTermNF33NerdFont-ExtraLightItalic.ttf
-rw-r--r-- 1 hp hp 2361928 12月 4日 21:15 MapleTermNF33NerdFont-ExtraLight.ttf
-rw-r--r-- 1 hp hp 2382140 12月 4日 21:15 MapleTermNF33NerdFont-Italic.ttf
-rw-r--r-- 1 hp hp 2382704 12月 4日 21:15 MapleTermNF33NerdFont-LightItalic.ttf
-rw-r--r-- 1 hp hp 2361532 12月 4日 21:16 MapleTermNF33NerdFont-Light.ttf
-rw-r--r-- 1 hp hp 2382508 12月 4日 21:16 MapleTermNF33NerdFont-MediumItalic.ttf
-rw-r--r-- 1 hp hp 2361448 12月 4日 21:16 MapleTermNF33NerdFont-Medium.ttf
-rw-r--r-- 1 hp hp 2360928 12月 4日 21:16 MapleTermNF33NerdFont-Regular.ttf
-rw-r--r-- 1 hp hp 2382396 12月 4日 21:15 MapleTermNF33NerdFont-SemiBoldItalic.ttf
-rw-r--r-- 1 hp hp 2361460 12月 4日 21:16 MapleTermNF33NerdFont-SemiBold.ttf
-rw-r--r-- 1 hp hp 2382088 12月 4日 21:16 MapleTermNF33NerdFont-ThinItalic.ttf
-rw-r--r-- 1 hp hp 2361300 12月 4日 21:15 MapleTermNF33NerdFont-Thin.ttf
```

**Comment by atauzki** [comment]
And the generated font name is also not right:
![image](https://github.com/user-attachments/assets/247ea712-7dce-483d-9ce6-6dd6bb973f10)

**Comment by subframe7536** [comment]
Thanks for reporting, I will fix it today.

**Comment by subframe7536** [comment]
Fixed. And the built-in Nerd Font version is upgrade to 3.3.0

**Comment by atauzki** [comment]
one glyph is missing vs patcher version. U+F1AF0
![image](https://github.com/user-attachments/assets/3428a5f3-89c7-4a3d-bea3-d67f4c29199f)

**Comment by subframe7536** [comment]
Cause by https://github.com/subframe7536/maple-font/blob/baaa419970ca423e53b9ffc1f7d5f77cdbc9c087/build_base_nf.py#L115

**Comment by atauzki** [comment]
and 23fb-23fe, 276c, 276d

**Comment by subframe7536** [comment]
I find that the `Font-Patcher.zip` contains a json file that have all the glyph names and unicode. I will determine the range from it

**Comment by subframe7536** [comment]
Fixed

**Comment by subframe7536** [comment]
Seems correct

![image](https://github.com/user-attachments/assets/82e83adb-985e-4e68-8ba9-1fbe3505f055)

**Comment by atauzki** [comment]
should be removed icons. e.g. F0387 and F0388 is the same, and F0388 is removed.
